{{ info.name }}
{{ info.created_at }}
{{ info.public_repos }}
{{ info.public_gists }}
{{ info.name }}
{{ info.created_at }}
{{ info.html_url }}
{{ info.updated_at }}
{{ info.avatar_url }}
{{ info.location }}
{{ info.email }}